# SPDX-License-Identifier: MIT
---
overpass__user: overpass
overpass__basedir: /srv/overpass
overpass__logdir: /var/log/overpass
overpass__version: 0.7.59.3
# Meta data to index. One of: no, meta, attic
overpass__meta_mode: attic
# Compression mode for the database. One of: no, gz, lz4
overpass__compression_mode: lz4
overpass__clone_url: "http://dev.overpass-api.de/api_drolbr"
overpass__replication_url: "https://planet.openstreetmap.org/replication/minute/"

overpass__rate_limit: 2
overpass__dispatcher_space: 10GB

overpass__acme_certificates:
  - name: overpass
    domains:
      - overpass-api.de
      - www.overpass-api.de
    on_update:
      - systemctl reload apache2
  - name: overpass_munin
    domains:
      - munin.lambert.openstreetmap.de
    on_update:
      - systemctl reload apache2
