# SPDX-License-Identifier: MIT
---
overpass__user: overpass
overpass__basedir: /srv/overpass
overpass__logdir: /var/log/overpass
overpass__version: 0.7.61.2
# Meta data to index. One of: no, meta, attic
overpass__meta_mode: attic
# Compression mode for the database. One of: no, gz, lz4
overpass__compression_mode: lz4
overpass__clone_url: "http://dev.overpass-api.de/api_drolbr/"
overpass__replication_url: "https://planet.openstreetmap.org/replication/minute/"

overpass__rate_limit: 6
overpass__dispatcher_space: 24GB

overpass__is_clone_origin: false

overpass__acme_certificates:
  - name: overpass
    domains:
      - overpass-api.de
      - www.overpass-api.de
      - z.overpass-api.de
      - lz4.overpass-api.de
    on_update:
      - systemctl reload apache2
  - name: overpass_munin
    domains:
      - "munin.{{ ansible_host }}"
    on_update:
      - systemctl reload apache2
