tile__basedir: /srv/tile
tile__user: tile

tile__style_version: v5.9.0-de7
tile__osml10n_version: v1.3.0
tile__map_hrb_version: cd48ece9f95f9d268ea9217492efef5d9e9f7ef4

tile__dbname: gis

# tile__small = true will make it load only a small extract
# tile__small = false will load the whole planet
# This value may be overwritten with an entry in the host_vars (host_vars/ptolemy.yml or host_vars/bonne.yml)
tile__small: true

# location of flatnode file
tile__flatnode: '{{ tile__basedir }}/flatnode'
# storage for planet pbf file during import
tile__planet: '{{ tile__basedir }}/planet.osm.pbf'


tile__acme_certificates:
  - name: tilede
    domains:
      - tile.openstreetmap.de
      - a.tile.openstreetmap.de
      - b.tile.openstreetmap.de
      - c.tile.openstreetmap.de
      - d.tile.openstreetmap.de
    on_update:
      - systemctl reload apache2
  - name: munin
    domains:
      - "{{ munin__hostname | regex_replace(':.*', '') }}"
    on_update:
      - systemctl reload apache2

icinga2customcheck__addon:
 - check_osmdataimport_timestamp
 - check_connections
