# SPDX-License-Identifier: MIT
---
wordpress_import_dumps: false
wordpress:
  version: '5.8.3'
  tarball_sha1: '3be7ed4dc6f46fe98271b974c88153640e95ad49'
  hostname: 'weeklyosm.eu'
  hostname_aliases:
    - 'www.weeklyosm.eu'
    - 'soldner.openstreetmap.de'
mariadb:
  socket_path: '/var/run/mysqld/mysqld.sock'

weeklyosm__acme_certificates:
  - name: weeklyosm
    domains:
      - weeklyosm.eu
      - www.weeklyosm.eu
    on_update:
      - systemctl reload apache2
