# SPDX-License-Identifier: MIT
---
wordpress_import_dumps: 'false'
wordpress:
  version: '5.8.1'
  #tarball_sha1: 'd5f1e6d7cadd72c11d086a2e1ede0a72f23d993e'
  hostname: 'weeklyosm.eu'
  hostname_aliases:
    - 'www.weeklyosm.eu'
    - 'soldner.openstreetmap.de'
mariadb:
  socket_path: '/var/run/mysqld/mysqld.sock'
