# SPDX-License-Identifier: MIT
---
wordpress_import_dumps: false
wordpress:
  version: '6.8.2'
  tarball_sha1: '03baad10b8f9a416a3e10b89010d811d9361e468'
  hostname: 'weeklyosm.eu'
  hostname_aliases:
    - 'www.weeklyosm.eu'
    - 'aitov.openstreetmap.de'
  hostnames:
    - 'weeklyosm.eu'
    - 'www.weeklyosm.eu'
    - 'aitov.openstreetmap.de'
mariadb:
  socket_path: '/var/run/mysqld/mysqld.sock'

weeklyosm__acme_certificates:
  - name: weeklyosm
    domains:
      - weeklyosm.eu
      - www.weeklyosm.eu
    on_update:
      - systemctl reload apache2
