# SPDX-License-Identifier: MIT
---
wordpress_import_dumps: false
wordpress:
  version: '6.0'
  tarball_sha1: '7a5a6d0591771e730b05c49d0c3fc134624d0491'
  hostname: 'weeklyosm.eu'
  hostname_aliases:
    - 'www.weeklyosm.eu'
    - 'soldner.openstreetmap.de'
  hostnames:
    - 'weeklyosm.eu'
    - 'www.weeklyosm.eu'
    - 'soldner.openstreetmap.de'
mariadb:
  socket_path: '/var/run/mysqld/mysqld.sock'

weeklyosm__acme_certificates:
  - name: weeklyosm
    domains:
      - weeklyosm.eu
      - www.weeklyosm.eu
    on_update:
      - systemctl reload apache2
