# SPDX-License-Identifier: MIT
---
wordpress_import_dumps: false
wordpress:
  version: '6.4.3'
  tarball_sha1: 'ee3bc3a73ab3cfa535c46f111eb641b3467fa44e'
  hostname: 'weeklyosm.eu'
  hostname_aliases:
    - 'www.weeklyosm.eu'
    - 'aitov.openstreetmap.de'
  hostnames:
    - 'weeklyosm.eu'
    - 'www.weeklyosm.eu'
    - 'aitov.openstreetmap.de'
mariadb:
  socket_path: '/var/run/mysqld/mysqld.sock'

weeklyosm__acme_certificates:
  - name: weeklyosm
    domains:
      - weeklyosm.eu
      - www.weeklyosm.eu
    on_update:
      - systemctl reload apache2
