- name: Check for apache
  fail:
    msg: nginx and apache cannot be run together.
  when: "(webserver__in_use | default('nginx')) != 'nginx'"

- name: Mark nginx the hosts webserver
  set_fact:
    webserver__in_use: nginx

- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: Disable default nginx site
  nginx_site:
    site: default
    state: absent
  when: webserver__default_site | default(False)

- name: Enable status export for munin
  nginx_site:
    site: munin-status-export
    src: nginx_munin_status.jinja
  when: "'munin' in ansible_role_names"
  notify: reload nginx

- name: Configure anonymized IP addresses
  copy:
    src: 'log_anonymized.conf'
    dest: '/etc/nginx/conf.d/log_anonymized.conf'
  notify: restart nginx

- name: Configure Nginx compression
  copy:
    dest: /etc/nginx/conf.d/gzip.conf
    content: |
      # Compression settings
      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_buffers 16 8k;
      gzip_http_version 1.1;
      gzip_min_length 1000;
      gzip_types
        application/atom+xml
        application/geo+json
        application/javascript
        application/x-javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rdf+xml
        application/rss+xml
        application/xhtml+xml
        application/xml
        font/eot
        font/otf
        font/ttf
        image/svg+xml
        text/css
        text/javascript
        text/plain
        text/xml;
    mode: '0644'
  notify: reload nginx
