- name: Check for apache
  fail:
    msg: nginx and apache cannot be run together.
  when: "(webserver__in_use | default('nginx')) != 'nginx'"

- name: Mark nginx the hosts webserver
  set_fact:
    webserver__in_use: nginx

- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: Disable default nginx site
  nginx_site:
    site: default
    state: absent
  when: webserver__default_site | default(False)

- name: Enable status export for munin
  nginx_site:
    site: munin-status-export
    src: nginx_munin_status.jinja
  when: "'munin' in ansible_role_names"
  notify: reload nginx

- name: Configure anonymized IP addresses
  copy:
    src: 'log_anonymized.conf'
    dest: '/etc/nginx/conf.d/log_anonymized.conf'
  notify: restart nginx
