# roles/weeklyosm/defaults/main.yml
---
weeklyosm_directory: "/srv/weeklyosm/www"
weeklyosm_deploy_user: "deploy-weekly"
weeklyosm_deploy_key: "ssh-ed25519
    AAAAC3NzaC1lZDI1NTE5AAAAIBijSeiqaFsWagRuCyFLogXJq3PXPzCucrPzVm6VWiFn
    deploy-weeklyosm@gitlab"

# comment service
weeklyosm__remark42__directory: "/srv/remark42"
weeklyosm__remark42__version: "v1.16.4"
weeklyosm__remark42__site_url: "https://hugo.weeklyosm.eu/comments"
weeklyosm__remark42__site_id: "weeklyosm"
weeklyosm__remark42__smtp_from: "weeklyOSM comments <noreply@weeklyosm.eu>"
weeklyosm__remark42__admin_email: "info@weeklyosm.eu"
weeklyosm__remark42__email_template_brand: "weeklyOSM"
# MatthiasMatthias = openstreetmap_d1d85c99139ab641f364ff686cc85bdc6457e5ce
# Strubbl = openstreetmap_f9fed4b96f1ad399793a6c534d8e67384eae11a2
weeklyosm__remark42__admin_id: "openstreetmap_d1d85c99139ab641f364ff686cc85bdc6457e5ce,openstreetmap_f9fed4b96f1ad399793a6c534d8e67384eae11a2"
