networks:
  reverseproxy_web:
    name: reverseproxy_web
#    external: true

services:

  db:
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 2s
    image: postgis/postgis:16-3.4-alpine
    container_name: umap_db
    env_file: ./database.env
    volumes:
      - umap_db:/var/lib/postgresql/data
      - ./umap_init_db.sh:/docker-entrypoint-initdb.d/01-init_umap_db.sh
      #- ./backup/umap_db.backup.sql:/tmp/umap_db.backup.sql:ro
    networks:
      - reverseproxy_web

  app:
    depends_on:
      db:
        condition: service_healthy
    image: umap/umap:2.6.3
    container_name: umap_app
    ports:
      - "8000:8000"
    volumes:
      - ./backup/var/data:/srv/umap/data
      - ./backup/custom:/srv/umap/custom
      - ./umap.conf:/etc/umap/umap.conf
      - ./iconpacks/osmic:/tmp/iconimport
    restart: always
    networks:
      - reverseproxy_web

volumes:
  umap_db:
