#!/bin/bash
#
# Set up a vagrant.ini inventory pointing at one or more running Vagrant VMs.
#
# Usage:
#   ./init_vagrant_inventory.sh VM [VM ...]
#
# Make sure the referenced VMs are running before invoking.
#
# Single-VM mode (backwards-compatible with the legacy `vagrant` host idiom):
#   ./init_vagrant_inventory.sh trixie
#     -> writes vagrant.ini with `vagrant ansible_host=...`. If vagrant.ini
#        already exists, just refreshes the IP/Port/IdentityFile in place.
#        Edit the file afterwards to put `vagrant` into the group you want.
#
# Multi-VM mode (e.g. the two-VM valhalla test setup):
#   ./init_vagrant_inventory.sh valhalla-service valhalla-builder
#     -> writes a fresh vagrant.ini with each VM under its own name. Known
#        VMs (see KNOWN_IPS / KNOWN_GROUPS below) are placed into the right
#        ansible group automatically; other names land in
#        `[your test group]` for you to edit.
#
# For known multi-VM setups the script uses the libvirt private_network IPs
# from Vagrantfile (rather than vagrant ssh-config's NAT'd 127.0.0.1:port).
# A single address that works both from the ansible controller and between
# peer VMs (graph push, deploy trigger) keeps the cross-host wiring honest.

set -e

if [ $# -lt 1 ]; then
    echo "usage: $0 VM [VM ...]" >&2
    exit 2
fi

CONFIG=vagrant.ini

# Keep in sync with Vagrantfile's private_network blocks.
declare -A KNOWN_IPS=(
    [valhalla-service]=192.168.123.10
    [valhalla-builder]=192.168.123.11
)
declare -A KNOWN_GROUPS=(
    [valhalla-service]=valhalla_service
    [valhalla-builder]=valhalla_builder
)

# Single-arg legacy path: preserve the historical `vagrant` hostname idiom
# and the in-place coordinate refresh, so existing usage keeps working.
if [ $# -eq 1 ] && [ -z "${KNOWN_IPS[$1]+x}" ]; then
    VAGRANTCFG=$(vagrant ssh-config "$1")
    SSH_IP=$(echo "$VAGRANTCFG" | grep HostName | sed 's:.*HostName *::')
    SSH_Port=$(echo "$VAGRANTCFG" | grep Port | sed 's:.*Port *::')
    SSH_IdentityFile=$(echo "$VAGRANTCFG" | grep IdentityFile | sed 's:.*IdentityFile *::')

    if [[ -f $CONFIG ]]; then
        sed -i "s:vagrant ansible_host=[0-9.]*:vagrant ansible_host=$SSH_IP:" $CONFIG
        sed -i "s:ansible_port=[0-9]*:ansible_port=$SSH_Port:" $CONFIG
        sed -i "s:ansible_ssh_private_key_file=.*:ansible_ssh_private_key_file=$SSH_IdentityFile:" $CONFIG
    else
        cat > $CONFIG <<EOF
[servers]
vagrant ansible_host=$SSH_IP ansible_port=$SSH_Port ansible_ssh_private_key_file=$SSH_IdentityFile

[acme]
dummy

[your test group]
vagrant
EOF
    fi
    echo "wrote $CONFIG ($1 -> vagrant)"
    exit 0
fi

# Multi-VM mode: always rewrite vagrant.ini fresh.
declare -A SERVERS
declare -A BY_GROUP

for vm in "$@"; do
    sshcfg=$(vagrant ssh-config "$vm")
    identity=$(echo "$sshcfg" | grep IdentityFile | sed 's:.*IdentityFile *::')
    if [ -n "${KNOWN_IPS[$vm]+x}" ]; then
        host=${KNOWN_IPS[$vm]}
        port=22
    else
        host=$(echo "$sshcfg" | grep HostName | sed 's:.*HostName *::')
        port=$(echo "$sshcfg" | grep Port | sed 's:.*Port *::')
    fi
    SERVERS[$vm]="ansible_host=$host ansible_port=$port ansible_user=vagrant ansible_ssh_private_key_file=$identity"
    grp=${KNOWN_GROUPS[$vm]:-"your test group"}
    BY_GROUP[$grp]+="$vm"$'\n'
done

{
    echo "# Generated by init_vagrant_inventory.sh — rerun the script to refresh."
    echo "[servers]"
    for vm in "$@"; do
        echo "$vm ${SERVERS[$vm]}"
    done
    echo
    echo "[servers:vars]"
    # Vagrant VMs are throwaway and get fresh host keys on every recreate.
    # Don't let SSH's interactive accept-key prompt block ansible (would
    # surface as "Host key verification failed" / ssh_askpass errors), and
    # don't pollute the user's ~/.ssh/known_hosts with rotating vagrant keys.
    echo 'ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"'
    echo
    echo "[acme]"
    echo "dummy"
    echo
    for grp in "${!BY_GROUP[@]}"; do
        echo "[$grp]"
        printf '%s' "${BY_GROUP[$grp]}"
        echo
    done

    # Parent group [valhalla:children] mirrors hosts.ini, so that
    # group_vars/valhalla/{vars,vault}.yml resolves for either half.
    # Only emit if at least one valhalla_* group ended up populated.
    if [ -n "${BY_GROUP[valhalla_service]:-}" ] || [ -n "${BY_GROUP[valhalla_builder]:-}" ]; then
        echo "[valhalla:children]"
        echo "valhalla_service"
        echo "valhalla_builder"
        echo
    fi
} > $CONFIG

echo "wrote $CONFIG ($*)"
