---
- hosts: all
  gather_facts: no
  strategy: linear
  tasks:
    - setup:
      tags: always

      #    # Ensure you're not missing out on anything
      #    # Does a local git fetch, and ensures that the origin/master branch is
      #    # merged into your current branch.  If not, it `fail`s.
      #    - become: no
      #      delegate_to: localhost
      #      tags: always
      #      check_mode: no
      #      run_once: true
      #      block:
      #        - name: Check current ansible git repo
      #          local_action: command git fetch origin
      #          changed_when: False
      #        - name: Check ansible git repo head
      #          local_action: command git branch --merged HEAD --remotes --color=never
      #          changed_when: False
      #          register: branches_merged_in
      #        - fail: msg="There are changes on origin/master that you don't have"
      #          when: "'  origin/master' not in branches_merged_in.stdout_lines"

      # Prevent ansible from running on too many hosts at once (max 5)
      # ansible_play_hosts gets dynamically updated, so as hosts 'fail' this
      # will reduce. 'freeze' this variable before `fail`ing
    - set_fact: num_hosts_in_play="{{ ansible_play_hosts|length }}"
      tags: always
    - fail: msg="Refusing to run on {{ num_hosts_in_play }} hosts at once"
      when: "num_hosts_in_play|int > 5"
      check_mode: no
      tags: always

    - name: 'Prevent tag "never" to be run on more than one host'
      when: "'never' in ansible_run_tags"
      tags: always
      #check_mode: no
      fail:
        msg: 'DANGER! You are running the tag "never" on more than one host. For safety reasons, this is not permitted because tasks tagged with "never" edit user accounts and or networking. The risk to break things is too high.'

#
# Regular playbooks here
#
- hosts: all
  tags: always
  tasks:
    - name: Load private variables
      include_vars:
        dir: private/vars
      ignore_errors: yes

- hosts: all
  become: yes
  tags: common
  roles:
    - role: common
- hosts: acme
  become: yes
  tasks:
    - include_role:
        name: letsencrypt
      tags: [letsencrypt,certificates]
- hosts: wordpress
  become: yes
  tags: wordpress
  roles:
    - role: 'wordpress'
- hosts: osrm
  become: yes
  tags: osrm
  roles:
    - role: osrm
- hosts: t3dmr
  become: yes
  roles:
    - role: t3dmr
- hosts: dns
  tags: dns
  become: yes
  roles:
    - role: dns
- hosts: static
  become: yes
  tags: static
  roles:
    - role: static
- hosts: overpass
  become: yes
  tags: overpass
  roles:
    - role: overpass
- hosts: overpass_dev
  become: yes
  tags: overpass_dev
  roles:
    - role: overpass_dev
