# SPDX-License-Identifier: MIT
- name: restart request-by-coordinate
  service:
    name: request-by-coordinate
    state: restarted
    enabled: yes
- name: restart munin-node
  service:
    name: munin-node
    state: restarted
    enabled: yes
