# SPDX-License-Identifier: MIT
---
- name: "Install MariaDB, and python3-pymysql as required by Ansible"
  apt:
    name: [mariadb-server, php, php-mysql, php-curl, php-gd, php-imagick, php-mbstring, php-xml, php-xmlrpc, php-soap, php-intl, php-zip, php-opcache, python3-pymysql, tar, gzip, unzip]

- name: Install php-fpm
  apt:
    name:
      - php-fpm
  when: wordpress__phpfpm

- name: Enable apache2 modules for phpfpm
  apache_module:
    name: "{{ item }}"
  with_items:
    - proxy_fcgi
    - setenvif
  notify: apache2 restart
  when: wordpress__phpfpm

- name: Disable apache2 modules for phpfpm
  apache_module:
    name: "php{{ wordpress__phpversion }}"
    state: absent
  notify: apache2 restart
  when: wordpress__phpfpm

- name: Enable config for phpfpm
  shell: "a2enconf {{ wordpress__apache2phpfpmconf }}"
  args:
    creates: "/etc/apache2/conf-enabled/{{ wordpress__apache2phpfpmconf }}.conf"
  notify: apache2 restart
  when: wordpress__phpfpm

- name: Create opcache directory
  file:
    path: "{{ wordpress__phpopcachepath }}"
    owner: www-data
    group: www-data
    mode: 0755
    state: directory
  when: wordpress__phpopcache

- name: Enable opcache in php
  ini_file:
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    dest: "{{ wordpress__phpini }}"
  with_items:
    - { section: "opcache", option: "opcache.enable", value: "1" }
    - { section: "opcache", option: "opcache.interned_strings_buffer", value: "64" }
    - { section: "opcache", option: "opcache.memory_consumption", value: "256" }
    - { section: "opcache", option: "opcache.revalidate_freq", value: "60" }
    - { section: "opcache", option: "opcache.file_cache", value: "{{ wordpress__phpopcachepath }}" }
    - { section: "opcache", option: "opcache.revalidate_freq", value: "60" }
  when: wordpress__phpopcache
  notify:
    - apache2 restart
    - phpfpm restart

- name: Configure php-fpm
  ini_file:
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    dest: "{{ wordpress__phpfpmpoolconf }}"
  with_items:
    - { section: "www", option: "pm.max_children", value: "{{ wordpress__phpfpmmaxchildren }}" }
    - { section: "www", option: "slowlog", value: "syslog" }
    - { section: "www", option: "request_slowlog_timeout", value: "20" }
  when: wordpress__phpfpm
  notify:
    - phpfpm reload

- name: Disable mpm_event, enable mpm_prefork and ignore warnings about missing mpm module
  apache_module:
    name: "{{ item.module }}"
    state: "{{ item.state }}"
    warn_mpm_absent: false
    ignore_configcheck: true
  loop:
  - module: mpm_event
    state: absent
  - module: mpm_prefork
    state: present
  when: wordpress__phpfpm

- name: "Create database for Wordpress"
  mysql_db:
    name: wpblog
    login_user: root
    login_unix_socket: '{{ mariadb.socket_path }}'

# TODO Ideally, we should do this in a smarter way and only write the rendered template if necessary, not at every run.
- name: Create a random password for Wordpress accessing MariaDB database and various secret keys/salts for cookies/temporary tokens
  set_fact:
    mysql_password: "{{ lookup('password', '/dev/null length=12') }}"
    wordpress_secret_key: "{{ lookup('password', '/dev/null length=42') }}"
    wordpress_auth_key: "{{ lookup('password', '/dev/null length=64') }}"
    wordpress_secure_auth_key: "{{ lookup('password', '/dev/null length=81') }}"
    wordpress_logged_in_key: "{{ lookup('password', '/dev/null length=64') }}"
    wordpress_nonce_key: "{{ lookup('password', '/dev/null length=64') }}"
    wordpress_auth_salt: "{{ lookup('password', '/dev/null length=64') }}"
    wordpress_secure_auth_salt: "{{ lookup('password', '/dev/null length=64') }}"
    wordpress_logged_in_salt: "{{ lookup('password', '/dev/null length=64') }}"
    wordpress_nonce_salt: "{{ lookup('password', '/dev/null length=64') }}"

- name: "Create database user for Wordpress"
  mysql_user:
    name: wpblog
    #TODO change password or write it to the configuration
    password: "{{ mysql_password }}"
    state: present
    priv: 'wpblog.*:ALL'
    login_user: root
    login_unix_socket: '{{ mariadb.socket_path }}'

- name: "Import dumps"
  when: wordpress_import_dumps
  block:
    - name: "Create directory /root/packages"
      file:
        state: directory
        path: '/root/packages'
        owner: root
        group: root

    #- local_action:
    #    stat:
    #      path: "../files_to_upload/host/{{ inventory_hostname }}/{{ item }}/"
    #  register: "local_exists_{{ item }}"
    #  loop:
    #    - "blog.openstreetmap.de_dir_var_www_wordpress"
    #    - "blog.openstreetmap.de_dir_var_lib_wordpress"
    #    - "blog.openstreetmap.de_mariadb_wpblog"

    #- when: "{{ item }}.changed == False"
    #  fail:
    #    msg: "Missing dump {{ item }}"
    #  loop:
    #    - "blog.openstreetmap.de_dir_var_www_wordpress"
    #    - "blog.openstreetmap.de_dir_var_lib_wordpress"
    #    - "blog.openstreetmap.de_mariadb_wpblog"

    #- name: "Upload Wordpress database and directory dumps ({{ item }})"
    #  synchronize:
    #    src: "../files_to_upload/host/{{ inventory_hostname }}/{{ item }}/"
    #    dest: "/"
    #    owner: no
    #    group: no
    #    perms: no
    #    rsync_opts: ["--omit-dir-times"]
    #  loop:
    #    - "blog.openstreetmap.de_dir_var_www_wordpress"
    #    - "blog.openstreetmap.de_dir_var_lib_wordpress"
    #    - "blog.openstreetmap.de_mariadb_wpblog"

    - name: "Download Wordpress"
      get_url:
        url: 'https://wordpress.org/wordpress-{{ wordpress.version }}.tar.gz'
        checksum: 'sha1:{{ wordpress.tarball_sha1 }}'
        dest: '/root/packages/wordpress-{{ wordpress.version }}.tar.gz'
    
    - name: "Unpack Wordpress tarball"
      unarchive:
        remote_src: yes
        src: '/root/packages/wordpress-{{ wordpress.version }}.tar.gz'
        dest: '/var/www/'
        owner: www-data
        group: www-data
        #mode: 0644

- name: "Create directory /etc/wordpress"
  file:
    state: directory
    path: '/etc/wordpress'
    owner: root
    group: root

- name: "Set MariaDB password in Wordpress configuration"
  template:
    dest: /etc/wordpress/config-default.php
    src: 'config-default.php'
    owner: 'www-data'
    group: 'www-data'
    mode: '0644'

- name: "Create directory /var/www/wordpress"
  file:
    state: directory
    path: '/var/www/wordpress'
    owner: 'www-data'
    group: 'www-data'

- name: "Add Wordpress configuration redirect/include placeholder"
  template:
    dest: /var/www/wordpress/wp-config.php
    src: 'wp-config.php'
    owner: 'www-data'
    group: 'www-data'
    mode: '0644'

- name: "Check if database has been imported already"
  mysql_table_exists:
    db: wpblog
    name: wp_posts
  register: database_imported

#- name: "Load database dump if the database has not been imported already"
#  when: not database_imported.table_exists
#  block:
#    - name: "Check if database dump is available"
#      stat:
#        path: /root/packages/wpblog_dump.sql.gz
#      register: stat_result
#
#    - name: 'Fail if database dump is not present'
#      when: not stat_result.stat.exists
#      fail:
#        msg: 'Require database dump at /root/packages/wpblog_dump.sql.gz in order to be able to load it in the next step.'
#
#    - name: 'Load database dump'
#      shell:
#        cmd: 'gzip -dc /root/packages/wpblog_dump.sql.gz | mysql --user root --database wpblog'

- name: 'Write Apache VirtualHost configuration'
  apache_site:
    site: weeklyosm.eu
    src: 'weeklyosm.eu.conf'
  notify: reload apache2

- name: "Create directories in /etc/systemd/system/ for overrides"
  file:
    state: directory
    path: '/etc/systemd/system/{{ item }}.service.d'
    owner: root
    group: root
  loop:
    - mariadb
    - apache2

- name: "set lower 'Out of memory adjust' score for database"
  copy:
    dest: '/etc/systemd/system/mariadb.service.d/override.conf'
    content: |
        [Service]
        OOMScoreAdjust=-600

- name: "ensure apache is always restarted if it dies"
  copy:
    dest: '/etc/systemd/system/apache2.service.d/override.conf'
    content: |
        [Service]
        Restart=always
        RestartSec=30s
