# SPDX-License-Identifier: MIT
---

- name: Install Wordpress
  include_tasks: install.yml
  tags: wordpress

- name: Install plugins
  include_tasks: plugins.yml
  tags: wordpress

- name: Install themes
  include_tasks: themes.yml
  tags: wordpress
