# roles/wordpress/tasks/themes.yml
# Installs themes from the Wordpress Theme Directory
---

- name: Create directory for themes
  file:
    dest: "{{ wordpress_theme_directory }}"
    state: directory

## themes with a version number, e.g.
#
# wordpress_themes:
#   - name: foo
#     version: 1.0.0
#   - name: bar
#     version: 4.2.0

- name: Download themes with version numbers
  get_url:
    url: "https://downloads.wordpress.org/theme/{{ item.name }}.{{ item.version }}.zip"
    dest: "/tmp/{{ item.name }}.{{ item.version }}.zip"
    force: false
  loop: "{{ wordpress_themes|flatten(levels=1) }}"
  when: item.version is defined
  tags: wordpress

- name: Unpack themes with version numbers
  unarchive:
    src: "/tmp/{{ item.name }}.{{ item.version }}.zip"
    dest: "{{ wordpress_theme_directory }}"
    creates: "{{ wordpress_theme_directory }}/{{ item.name }}"
    copy: false
  loop: "{{ wordpress_themes|flatten(levels=1) }}"
  when: item.version is defined
  tags: wordpress

## themes without a version number, e.g.
#
# wordpress_themes:
#   - name: foo
#   - name: bar

- name: Download themes without version numbers
  get_url:
    url: "https://downloads.wordpress.org/theme/{{ item.name }}.zip"
    dest: "/tmp/{{ item.name }}.zip"
    force: false
  loop: "{{ wordpress_themes|flatten(levels=1) }}"
  when: item.version is not defined
  tags: wordpress

- name: Unpack themes without version numbers
  unarchive:
    src: "/tmp/{{ item.name }}.zip"
    dest: "{{ wordpress_theme_directory }}"
    creates: "{{ wordpress_theme_directory }}/{{ item.name }}"
    copy: false
  loop: "{{ wordpress_themes|flatten(levels=1) }}"
  when: item.version is not defined
  tags: wordpress

## unpack customized child theme for weeklyosm style adaptations:

- name: Install weeklyOSM child theme
  copy:
    dest: /var/www/wordpress/wp-content/themes/
    src: 'weekly-child-theme/'
    directory_mode:
    owner: 'www-data'
    group: 'www-data'
    mode: '0644'
