# SPDX-License-Identifier: MIT
---
- name: Create deploy user and directories
  include_tasks: hugopermissions.yml
  tags: weeklyosm

- name: Set up Remark42 comment service
  include_tasks: commentsystem.yml
  tags: weeklyosm

- name: Set up nginx site
  nginx_site:
      site: hugo.weeklyosm.eu
      src: hugo.weeklyosm.eu.conf.j2
  vars:
      # exclude newsletter subdomain which routes to listmonk
      hugo_hostnames: "{{ weeklyosm.hostnames | reject('equalto', 'newsletter.weeklyosm.eu') | list }}"
  notify: reload nginx
  tags: weeklyosm
