# SPDX-License-Identifier: MIT
---
- name: Create deploy user and directories
  ansible.builtin.include_tasks: permissions.yml
  tags: weeklyosm

- name: Configure webserver
  ansible.builtin.include_tasks: webserver.yml
  tags: weeklyosm
