# SPDX-License-Identifier: MIT
---
- name: "Install rsync package"
  package:
    name: rsync
    state: present

- name: "Deploy rsync-restriction script (rrsync)"
  shell: |
    # find rrsync
    RRSYNC_SRC=$(find /usr/share/doc/rsync -name "rrsync.gz" | head -n 1)
    if [ -n "$RRSYNC_SRC" ]; then
      gunzip -c "$RRSYNC_SRC" > /usr/bin/rrsync
      chmod +x /usr/bin/rrsync
    elif [ -f "/usr/share/doc/rsync/scripts/rrsync" ]; then
      # already uncompressed, e.g. on Debian/Ubuntu
      cp /usr/share/doc/rsync/scripts/rrsync /usr/bin/rrsync
      chmod +x /usr/bin/rrsync
    fi
  args:
    creates: /usr/bin/rrsync

- name: "Create upload user for static website"
  user:
    name: "{{ weeklyosm_deploy_user }}"
    # rsync needs a home to place the .ssh/authorized_keys
    create_home: yes
    home: "/home/{{ weeklyosm_deploy_user }}"
    shell: /bin/bash

- name: "Create target directory"
  file:
    path: "{{ weeklyosm_directory }}"
    state: directory
    owner: "{{ weeklyosm_deploy_user }}"
    group: "www-data"
    mode: 755

- name: "install public key with rsync restriction"
  authorized_key:
    user: "{{ weeklyosm_deploy_user }}"
    key: >
      command="/usr/bin/rrsync {{ weeklyosm_directory
      }}",no-agent-forwarding,no-port-forwarding,no-pty  {{ weeklyosm_deploy_key
      }}
