
- name: "create script directory"
  file:
    path: '{{ osrm__basedir }}/scripts'
    state: directory
    owner: '{{ osrm__user }}'
    group: '{{ osrm__user }}'

- name: "new graphs script"
  template:
    dest: "{{ osrm__basedir }}scripts/newgraphs.sh"
    src: "new-graphs.j2"
    mode: 0755

- name: "cron new graphs"
  cron:
    name: osrm new graphs
    cron_file: osrm_newgraphs
    minute: "28,58"
    job: "{{ osrm__basedir }}scripts/newgraphs.sh"
    user: root

