
- name: "new graphs script"
  template:
    dest: "{{ osrm.basedir }}scripts/newgraphs.sh"
    src: "new-graphs.j2"

- name: "cron new graphs"
  template:
    dest: "/etc/cron.d/new-graphs"
    src: "cron-new-graphs.j2"

