# SPDX-License-Identifier: MIT
---
- hosts: all
  become: yes
  tags: mail
  tasks:
    - import_role:
        name: 'roles/mail'
      vars:
      when: mail | default(False)
- hosts: wordpress
  become: yes
  tags: wordpress
  tasks:
    - import_role:
        name: 'roles/wordpress'
    #- import_role:
    #    name: 'roles/letsencrypt'
    #  vars:
    #    certificate_alt_names: 'DNS:weeklyosm.eu, DNS:www.weeklyosm.eu, DNS:soldner.openstreetmap.de'
- hosts: osrm
  become: yes
  tags: osrm
  tasks:
    - import_role:
        name: 'roles/osrm'

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
    - name: restart request-by-coordinate
      service:
        name: request-by-coordinate
        state: restarted
        enabled: yes
    - name: restart munin-node
      service:
        name: munin-node
        state: restarted
        enabled: yes

