# roles/listmonk/defaults/main.yml
---
listmonk_version: "6.2.0"
listmonk_user: "listmonk"
listmonk_install_dir: "/srv/listmonk"
listmonk_backup_dir: "/var/backups"

listmonk_db_name: "listmonk"
listmonk_db_user: "listmonk"
listmonk_db_password: "overwrittenBy:PrivateVars"
