- name: apache2 restart
  systemd:
    name: apache2
    state: restarted

- name: phpfpm restart
  systemd:
    name: "{{ wordpress__fpmservice }}"
    state: restarted

- name: phpfpm reload
  systemd:
    name: "{{ wordpress__fpmservice }}"
    state: reloadedY

- name: Anubis restart
  ansible.builtin.systemd_service:
    name: "anubis@{{ __instance.name }}"
    state: restarted
  loop: "{{ anubis__instances }}"
  loop_control:
    loop_var: __instance
