# SPDX-License-Identifier: MIT
- name: 'reload ssh'
  systemd:
    name: 'ssh'
    state: 'reloaded'

- name: 'restart cron'
  systemd:
    name: cron
    state: restarted

- name: 'restart journald'
  systemd:
    name: systemd-journald
    state: restarted
