# SPDX-License-Identifier: MIT
---
- name: Install Postfix
  apt:
    name: [postfix]

- name: set /etc/mailname
  copy:
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
    content: |
      {{ inventory_hostname }}

- name: 'virtual_alias_map and bad_senders'
  include_tasks: write_and_hash.yml
  loop:
    - {'src': 'virtual_alias_map', 'dest': '/etc/postfix/virtual_alias_map', 'cmd': 'postalias'}

- name: Write /etc/postfix/main.cf
  template:
    dest: /etc/postfix/main.cf
    src: main.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - systemctl reload postfix

- name: Write /etc/postfix/master.cf
  copy:
    dest: /etc/postfix/master.cf
    src: master.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - systemctl reload postfix
