# SPDX-License-Identifier: MIT
- name: 'Create {{ item.dest }}'
  register: map_result
  copy:
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0644
    content: |
      {% for key, value in mail.aliases.items() %}
      {{ key }} {% if value is string %}{{ value }}{% else %}{{ value|join(',') }}
      {% endif %}

      {% endfor %}

- name: Run postmap if required on virtual_alias_map
  shell:
    cmd: '{{ item.cmd }} hash:{{ item.dest }}'
    chdir: /etc/postfix
  when: map_result.changed
  register: postmap_result

- name: Reload Postfix because postmap was executed
  systemd:
    name: postfix
    state: reloaded
  when: postmap_result.changed
