- name: Install sudo
  apt:
    name: sudo

- block:
    - name: Gather active accounts
      set_fact:
        accounts__active: "{{accounts__active|default([]) + [item.0.name]}}"
      when: "item.1 in group_names or item.1 == 'all'"
      loop: "{{ _users | subelements('groups', skip_missing=True) }}"

    - name: Create user accounts
      when: "item.name in accounts__active"
      user:
        name: "{{ item.name }}"
        groups: [sudo, adm]
        password: ""
        shell: "/bin/bash"
        update_password: on_create
      loop: "{{ _users }}"

    - name: "Remove users who do not have permissions to access this host"
      when: "item.name not in accounts__active"
      user:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ _users }}"

    - name: "Add SSH public keys"
      when: "item.0.name in accounts__active"
      authorized_key:
        user: "{{ item.0.name }}"
        key: "{{ item.1 }}"
      loop: "{{ _users|subelements('ssh_public_keys') }}"

    - name: "Add SSH public keys of all users for direct root login (required by Ansible)"
      when: "item.0.name in accounts__active"
      authorized_key:
        user: "root"
        key: "{{ item.1 }}"
      loop: "{{ _users|subelements('ssh_public_keys') }}"
  vars:
    _users: "{{ users | default([]) }}"
