- name: Install sudo
  apt:
    name: sudo

- block:
    - name: "Create user accounts"
      when: "item.hosts == 'all' or inventory_hostname in item.hosts"
      user:
        name: "{{ item.name }}"
        groups: [sudo, adm]
        password: ""
        shell: "/bin/bash"
        update_password: on_create
      loop: "{{ _users }}"

    - name: "Remove users who do not have permissions to access this host"
      when: "item.hosts != 'all' and inventory_hostname not in item.hosts"
      user:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ _users }}"

    - name: "Add SSH public keys"
      when: "item.0.hosts == 'all' or inventory_hostname in item.0.hosts"
      authorized_key:
        user: "{{ item.0.name }}"
        key: "{{ item.1 }}"
      loop: "{{ _users|subelements('ssh_public_keys') }}"

    - name: "Add SSH public keys of all users for direct root login (required by Ansible)"
      when: "item.0.hosts == 'all' or inventory_hostname in item.0.hosts"
      authorized_key:
        user: "root"
        key: "{{ item.1 }}"
      loop: "{{ _users|subelements('ssh_public_keys') }}"
  vars:
    _users: "{{ users | default([]) }}"
