# SPDX-License-Identifier: MIT
---

- name: Import tasks to create accounts
  import_tasks: accounts.yml
  tags: [never, accounts]

- name: Import tasks to install some utilities
  import_tasks: utilities.yml
  tags: base

- name: Import tasks to do some fundamental security settings
  import_tasks: security.yml
  tags: base

- name: Set up ACME certificate receival
  include_tasks: acme_cert_client.yml
  when: "hostvars[inventory_hostname]|var_merge_lists(suffix='__acme_certificates')"

- name: Import task to set timezone and locale
  import_tasks: timezone.yml
  tags: base

- import_role:
    name: 'roles/mail'
  vars:
  when: mail | default(False)
  tags: mail
