# SPDX-License-Identifier: MIT
---
- name: Disable SSH login without public key
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#? *PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
  notify:
    - reload ssh

    #- name: Install fail2ban
    #  apt:
    #    name: fail2ban
    #
    #- name: Customise fail2ban
    #  copy:
    #    dest: '/etc/fail2ban/jail.local'
    #    mode: 0644
    #    owner: root
    #    group: root
    #    content: |
    #        [DEFAULT]
    #        bantime = 20m
    #        findtime = 10m
    #        maxretry = 15
    #        [sshd]
    #        enabled = true
    #  notify:
    #    - reload fail2ban

- name: Install ufw
  apt:
    name: ufw

- name: 'ufw: allow SSH, HTTP and HTTPS'
  ufw:
    comment: 'allow {{ item.comment }}'
    rule: allow
    name: '{{ item.protocol }}'
  loop:
    - {'comment': 'SSH', 'protocol': 'OpenSSH'}
    - {'comment': 'HTTP+HTTPS', 'protocol': 'WWW Full'}
    - {'comment': 'SMTP', 'protocol': 'SMTP'}

- name: 'ufw: default deny'
  ufw:
    default: 'reject'

- name: 'ufw enable'
  ufw:
    state: enabled


- name: Set up unattended upgrades
  apt:
    name:
      - unattended-upgrades

- name: Enable unattended upgrades
  copy:
    src: /usr/share/unattended-upgrades/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    remote_src: yes
