# SPDX-License-Identifier: MIT
# Vagrant test VM for the valhalla service role. Pairs with valhalla-builder
# on a shared libvirt private_network (see Vagrantfile). No overrides needed
# at this layer — all builder-specific values (planet URL, SSH target, etc.)
# live in host_vars/valhalla-builder.yml.
