"~fincaraiz.com"        1;
"~lovable.app"          1;
"~vercel.app"           1;
"~base44.app"           1;
"~run.app"              1;
"~netlify.app"          1;
"~replit.dev"           1;
"~web.app"              1;
"~pages.dev"            1;
"~webcontainer.io"      1;
"~webcontainer-api.io"  1;
"~lovableproject.com"   1;
"~hauk.live"            1;
"~nbot.pl"              1;
"~zuniz.com"            1;
"~geo-fs.com"           1;
"~groupalarm.com"       1;
"~reality.sk"           1;
"~oaiusercontent.com"   1;
"~astegiudiziarie.it"   1;
"~pixelpirate.fr"       1;
"~finland-map.fi"       1;
"~infocasas.com"        1;
