"~^Python-urllib/"      1;
"~^python-requests/"    1;
"~^python-httpx/"       1;
"~^node$"               1;
"~^Go-http-client/"     1;
"~^Dart/"               1;
"~^GuzzleHttp/"         1;
"~^axios/"              1;
"~^okhttp/"             1;
"~^Jersey/"             1;
"~aiohttp"              1;
"~^libcurl-agent/"      1;
"~1C\+Enterprise"       1;
"~[Cc]rawl"             1;
"~[Pp]roperty"          1;
"~^speedmeter/1"        1;
"~^Speedometer"         1;
"~^Deno/"               1;
"~^GeoCats AGORA"       1;
"~^R8.Companion.Nav"    1;
"~^saved.archi "        1;
"~^arnis/"              1;
"~^xspeedkadran/1"      1;
"~^xspeed/1"            1;
"~^dspeed/1"            1;
"~^DukesR8App/"         1;
"~^Pelican/690 "        1;
"~^HighwayRadar/"       1;
"~^Bun/"                1;
"~^BeenToApp/"          1;
"~^Android/3168$"       1;
"~^playas-espana.com/"  1;
