postgresql__version: |-
  {{
      {
        '11': 13,
        '12': 15,
        '13': 17
      }[ansible_distribution_major_version]
  }}

postgresql__postgis_version: 3

postgresql__conf_shared_buffers: "1GB"
