---
- name: Set up postgresl user
  postgresql_user:
      name: "{{ listmonk__db_user }}"
      password: "{{ listmonk__db_password }}"
  become_user: postgres

- name: Create PostgreSQL database
  become_user: postgres
  community.postgresql.postgresql_db:
      name: "{{ listmonk__db_name }}"
      owner: "{{ listmonk__db_user }}"

- name: Create system user for Listmonk
  ansible.builtin.user:
      name: "{{ listmonk__user }}"
      system: true
      create_home: false

- name: Ensure installation directory exists
  ansible.builtin.file:
      path: "{{ listmonk__install_dir }}"
      state: directory
      owner: "{{ listmonk__user }}"
      group: "{{ listmonk__user }}"
      mode: "0755"

- name: Download and extract Listmonk binary
  ansible.builtin.unarchive:
      src: "https://github.com/knadh/listmonk/releases/download/v{{ listmonk__version }}/listmonk_{{ listmonk__version }}_linux_amd64.tar.gz"
      dest: "{{ listmonk__install_dir }}"
      remote_src: true
      owner: "{{ listmonk__user }}"
      group: "{{ listmonk__user }}"
      creates: "{{ listmonk__install_dir }}/listmonk"

- name: Ensure Listmonk binary is executable
  ansible.builtin.file:
      path: "{{ listmonk__install_dir }}/listmonk"
      mode: "0755"

- name: Deploy config.toml
  ansible.builtin.template:
      src: templates/config.toml.j2
      dest: "{{ listmonk__install_dir }}/config.toml"
      owner: "{{ listmonk__user }}"
      group: "{{ listmonk__user }}"
      mode: "0600"
  register: config_file

- name: Check if Listmonk DB is already initialized
  become_user: postgres
  community.postgresql.postgresql_query:
      login_db: "{{ listmonk__db_name }}"
      query: "SELECT to_regclass('public.subscribers');"
  register: db_check

- name: Initialize Listmonk Database (First install only)
  become_user: "{{ listmonk__user }}"
  ansible.builtin.command:
      cmd: "./listmonk --install --yes --config config.toml"
      chdir: "{{ listmonk__install_dir }}"
  vars:
      ansible_remote_tmp: /tmp
  when: db_check.query_result[0][0].to_regclass is none

- name: Deploy systemd service unit
  ansible.builtin.template:
      src: templates/listmonk.service.j2
      dest: "/etc/systemd/system/listmonk.service"
      mode: "0644"
  register: systemd_service

- name: Reload systemd, enable and start Listmonk
  ansible.builtin.systemd:
      name: listmonk
      state: restarted
      enabled: true
      daemon_reload: true
  when: systemd_service.changed or config_file.changed

- name: Ensure Listmonk service is running
  ansible.builtin.systemd:
      name: listmonk
      state: started
      enabled: true

- name: Set up nginx site
  nginx_site:
      site: newsletter.weeklyosm.eu
      src: newsletter.weeklyosm.eu.conf.j2
  notify: reload nginx
