# SPDX-License-Identifier: MIT
---
- name: Read private vars for Listmonk
  include_tasks: private_vars.yml
  tags: listmonk

- name: Backup Listmonk database before upgrade
  include_tasks: backup.yml
  tags: listmonk

- name: Install Listmonk
  include_tasks: install.yml
  tags: listmonk
