---
- name: Read private admin password if defined
  set_fact:
    listmonk_admin_password: "{{ listmonk_admin_password_private }}"
  tags: listmonk
  when: listmonk_admin_password_private is defined

- name: Read private db password if defined
  set_fact:
    listmonk_db_password: "{{ listmonk_db_password_private }}"
  tags: listmonk
  when: listmonk_db_password_private is defined
