- name: Install munin
  apt:
    name:
      - munin
      - munin-node
      - liblwp-useragent-determined-perl

- name: Install nginx plugins
  munin_plugin:
    name: "{{ item }}"
  loop:
    - nginx_request
    - nginx_status
  when: "webserver__in_use == 'nginx'"
  notify: restart munin-node

- name: Install apache plugins
  munin_plugin:
    name: "{{ item }}"
  loop:
    - apache_accesses
    - apache_processes
    - apache_volume
  when: "webserver__in_use == 'apache2'"
  notify: restart munin-node
