- name: Install munin
  apt:
    name:
      - munin
      - munin-node

- name: Install nginx plugins
  munin_plugin:
    name: "{{ item }}"
  loop:
    - nginx_request
    - nginx_status
  when: "'nginx' in ansible_role_names"
  notify: restart munin-node
