- name: Setup certificate renewal server
  include_tasks: acme_renewal_server_setup.yml
  tags: letsencrypt

- name: Update certificate configuration
  tags: certificates
  include_tasks: update_certificates.yml
  tags: [letsencrypt,certificates]
