# SPDX-License-Identifier: MIT
- name: systemctl reload postfix
  systemd:
    name: postfix
    state: reloaded

- name: systemctl restart postfix
  systemd:
    name: postfix
    state: restarted

- name: systemctl restart opendkim
  systemd:
    name: opendkim
    state: restarted
